In [1]:
import numpy as np
import pandas as pd

In [2]:
#take matrix
matrix = ([[1.5,1.7,2.5],[2,1.9,2.9],[1.6,1.8,2.0],[1.2,1.5,1.7],[1.0,1.6,3.0]])

In [3]:
#convet matrix into array
np.array(matrix)

array([[1.5, 1.7, 2.5],
       [2. , 1.9, 2.9],
       [1.6, 1.8, 2. ],
       [1.2, 1.5, 1.7],
       [1. , 1.6, 3. ]])

In [14]:
#For_Euclidean
from sklearn.metrics.pairwise import euclidean_distances

In [15]:
#these show the euclidean of teh matrix
euclidean_distances(matrix)

array([[0.        , 0.67082039, 0.51961524, 0.87749644, 0.71414284],
       [0.67082039, 0.        , 0.98994949, 1.49666295, 1.04880885],
       [0.51961524, 0.98994949, 0.        , 0.58309519, 1.18321596],
       [0.87749644, 1.49666295, 0.58309519, 0.        , 1.3190906 ],
       [0.71414284, 1.04880885, 1.18321596, 1.3190906 , 0.        ]])

In [16]:
# For_Manhattan
from scipy.spatial.distance import cdist

In [24]:
#these show the manhattan 
print(cdist(matrix, matrix, metric='cityblock'))

[[0.  1.1 0.7 1.3 1.1]
 [1.1 0.  1.4 2.4 1.4]
 [0.7 1.4 0.  1.  1.8]
 [1.3 2.4 1.  0.  1.6]
 [1.1 1.4 1.8 1.6 0. ]]
